(p2to3) yokotool: set subparsers as required
The handling of subparsers changed with Python3
and now when entering below command:
  $ ./yokotool

We get:
  AttributeError: 'Namespace' object has no attribute 'func'

Subparsers need to be set as "required = true",
so that we get the usual exception:
  yokotool: ERROR: the following arguments are required: , -h for help

Source http://bugs.python.org/issue16308

Change-Id: I54d5710fd28c8a4a069a7abc8a07686f3ebfa401
Signed-off-by: Helia Correia <helia.correia@linux.intel.com>