BUG FIX: catch empty parameters in "_verify_math_name()"
"set-math" command requires an argument but is verification
function wouldn't catch the case where the argument was empty,
leading to display below traceback.

---

Traceback (most recent call last):
  File "./yokotool", line 1044, in <module>
    sys.exit(main())
  File "./yokotool", line 1031, in main
    args.func(meter)
  File "./yokotool", line 700, in set_command
    meter.command(cmd, args.value)
  File "/home/dellxps12-first/yoko-tools-py3/yokolibs/PowerMeter.py", line 139, in command
    response = self._meter.command(cmd, arg)
  File "/home/dellxps12-first/yoko-tools-py3/yokolibs/_yokobase.py", line 424, in command
    self._verify_argument(cmd, arg)
  File "/home/dellxps12-first/yoko-tools-py3/yokolibs/_yokobase.py", line 390, in _verify_argument
    if not func(arg):
  File "/home/dellxps12-first/yoko-tools-py3/yokolibs/_wt310.py", line 248, in _verify_math_name
    match = re.search(r"([^\d]*)(\d+)$", name)
  File "/usr/lib/python3.4/re.py", line 170, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

Signed-off-by: Helia Correia <helia.correia@linux.intel.com>

Change-Id: Ic230ba3747c3b609ab83b81bc1f74aeac3895bca